### ISSUE TITLE
Multiple Names in same file nameChecker.py3 Issue

### ISSUE THREAD

**Issue by bibesh07** [bibesh07/Problem-Solving-Questions-Solutions#2]
@pratikshya7 your solution is not the best say if there are 10 files and names are repeated you need to make sure that the name is across all the files not 10 names in the same file. Please make sure and request a pull request. Thanks.

**Comment by pratikshya7** [comment]
Okay, I'll look into it and make sure there isn't a problem in there .

**Comment by bibesh07** [comment]
The issue has been solved. Thanks @pratikshya7 💯 .
